### ISSUE TITLE
XMLHttpRequest.send() doesn't return if server is dead

### ISSUE THREAD

**Issue by jeffpar** [jeffpar/pcjs.v1#1]
In [Computer.verifyUserID()](https://github.com/jeffpar/pcjs/blob/master/my_modules/pcjs-client/lib/computer.js#L955), an API request is performed with a call to web.loadResource(), which performs the aforementioned send().  If I deliberately kill the server while the client app is still running and then try to call verifyUserID() -- by clicking on the "Save" button on a resumable machine -- it silently fails.

How do I catch/detect this problem and report a sensible error?

**Comment by felipegtx** [comment]
Hey @jeffpar, I was wondering if this was already solved (maybe with [this approach](https://github.com/jeffpar/pcjs/blob/646acf3a8d302312fe7e273f57f2e1a623c2b491/modules/pcjs/lib/computer.js#L1065)) and if not, would [this be the line](https://github.com/jeffpar/pcjs/blob/646acf3a8d302312fe7e273f57f2e1a623c2b491/modules/pcjs/lib/computer.js#L1062) you're pointing  when you opened this issue back in Sep '14?

**Comment by jeffpar** [comment]
I'll have to get back to you on this next week when I return home and have access to a real computer. Thanks.

**Comment by jeffpar** [comment]
Those server APIs are no longer used, so I'm considering this a non-issue now.
