### ISSUE TITLE
CAPS-LOCK still an issue on Windows (Chrome)

### ISSUE THREAD

**Issue by jeffpar** [jeffpar/pcjs.v1#17]
I added a work-around for CAPS-LOCK handling in Internet Explorer, but the same work-around is apparently needed in Chrome for Windows.

Chrome for Mac behaves similar to Safari (CAPS-LOCK generates only a "down" event when locking, and only an "up" event when unlocking), but Chrome for Windows appears to be behave similar to MSIE (it generates both "down" and "up" events on both lock and unlock).

**Comment by felipegtx** [comment]
@jeffpar would you mind pointing out where did you put the "work-around" for IE? I'd like to give it a try on a fix for Chrome Win.

**Comment by jeffpar** [comment]
Good question. I think the Keyboard component (kbd.js) may have undergone a bit of a rewrite since that issue was opened, so I'll have to take a fresh look when I return home next week. Thanks.

**Comment by jeffpar** [comment]
This should be fixed as of the latest PCjs release.
