### ISSUE TITLE
Incorrect Date.now fallback

### ISSUE THREAD

**Issue by mihailik** [jeffpar/pcjs.v1#18]
https://github.com/jeffpar/pcjs/blob/b8407aa96d4fce2cc09ab64077aa188b4df69dbb/modules/shared/lib/usrlib.js#L91

```
usr.getTime = function() {
  return Date.now() || +new Date();
};
```

If Date.now is not defined, the code throws and never executed the +new Date part (as it does indeed in IE8 for example). How about:

```
usr.getTime = Date.now && Date.now() ? Date.now : function() { return +new Date(); };
```

**Comment by jeffpar** [comment]
Good point, I'll do as you suggest.  IE8 can't really support PCjs though, right?

**Comment by mihailik** [comment]
That's right, IE8 breaks in lots of other places too. And it's slow.

[ES5 compatibility table](http://kangax.github.io/compat-table/es5/) suggests Date.now is well supported. But it's missing mobile IE, Blackberry and others.
