### ISSUE TITLE
Allow hosting web page to handle requests, instead of going XHR

### ISSUE THREAD

**Issue by mihailik** [jeffpar/pcjs.v1#19]
For embedded scenarios, offline or file: protocol it would be cool to be able to intercept external requests for all the disks, manifests, devices and stuff and serve them from wherever the hosting page sees fit.

Currently I do it by wrapping the main pc.js script in a 'module'-like closure and feeding in window/XMLHttpRequest substitutes. Essentially a polyfill hack.

Would be much easier to support it natively.

For example, before constructing XMLHttpRequest check if embedPC.onfetch is a function and if so -- call it to get the response from there.

I'll try to play with it and if all goes well, will submit a pull request.

**Comment by jeffpar** [comment]
Cool, thanks.

**Comment by jeffpar** [comment]
A hosting web page can now do this by creating a global "resources" object that contains URL properties for every URL requested by the machine(s) on the page.  The value of each URL property must contain the same data that XMLHttpRequest would return for that URL.  This is what the blobs of JavaScript produced by the new "Save Machine" links do.

See getResource() in /modules/shared/lib/weblib.js, which is where all PCjs remote resource requests go.

**Comment by mihailik** [comment]
Brilliant! It would be great to allow optional async handling there too. I'll make a PR for that.
