### ISSUE TITLE
Expose API for taking/loading snapshots of VM

### ISSUE THREAD

**Issue by mihailik** [jeffpar/pcjs.v1#20]
Is there a way to dump memory, CPU and IO device state down to some JSON/XML mixture, then restart from that?

Similar how in the modern full-blown VM solutions you can make a snapshot and restart from it.

Given that the amount of RAM/disk in use is practically tiny, such a snapshot for pc.js can simply dump the whole state as is, rather than use deltas as in the big-gun warfare behemots.

**Comment by jeffpar** [comment]
There's no API for doing that, but that's a good idea. There is a Debugger command for dumping an entire machine's state ("d state"), which is what I use to create static state.json files for canned PCjs demos, but you have to be using a machine XML config with Debugger support.

One nice thing about PCjs states is that they also contain any deltas made to any of the disk images loaded from the server. Those deltas are reapplied on a restore (both from static state files or from states automatically saved in local storage), giving the appearance of read-write storage even though all the disk images are read-only.

**Comment by mihailik** [comment]
Really, so there is a way to do it already? Thanks a lot, that's fantastic!

**Comment by jeffpar** [comment]
Take a look at the savePC() function in /modules/shared/lib/save.js.  That's the interface used by the "Save Machine" links.  If you want to tweak the interface, feel free to send a pull request. Thanks.

**Comment by mihailik** [comment]
Thanks, I've picked on that and started to use it, it works fantastic.
