### ISSUE TITLE
Checkout and integrate Gitter.im

### ISSUE THREAD

**Issue by lenucksi** [jeffpar/pcjs.v1#25]
Hello,

I found Gitter.im (http://gitter.im) to be very usefull. It is a richtext (as in Markdown) and GitHub plus various other tools integrated chat service that provides a chat with a permanent archive for a repository that is available for free. 

Could you please have a look at it and maybe integrate it to your repo?

**Comment by ZaDarkSide** [comment]
+1

**Comment by jeffpar** [comment]
I think there's enough community services built into GitHub that we don't need this.  Thanks.
