### ISSUE TITLE
Win95 won't load

### ISSUE THREAD

**Issue by ghost** [jeffpar/pcjs.v1#42]
http://www.pcjs.org/disks/pcx86/windows/win95/4.00.950/ will not load. The loading bar appears to go backwards, and after a while it slows down.

**Comment by Octocontrabass** [comment]
What browser are you using? I'm using Firefox 47 and it loads fine, aside from the loading bar going backwards.

**Comment by jeffpar** [comment]
This has been well-tested, so I'll have to assume this was some sort of browser-specific problem.

**Comment by mihailik** [comment]
I can confirm the load bar indeed goes backwards (i.e. right to left) on all browsers I tried:

* Chrome v64.0  on Windows 7 64bit, 2 monitors 1920x1080
* Internet Explorer v11 (latest)  on Windows 7 64bit, 2 monitors 1920x1080

* Chrome v65  on Android 7.0 on Moto G4 Plus
* Edge 1.0.0.0  on Android 7.0 on Moto G4 Plus (one just released by Microsoft)
* FireFox v59  on Android 7.0 on Moto G4 Plus 

* Safari v11.0.1 on macOS Sierra 10.12.6 MacBook Pro (Retina)

Wonder if that's some kind of <a href="https://en.wikipedia.org/wiki/Stroboscopic_effect">strobe/wagon wheel effect</a> like below?

![helicopter strobe effect](https://i.kinja-img.com/gawker-media/image/upload/s--zy3qEhQV--/776619703021977520.gif)

Or is it a video glitch in that hacky mode Win95 uses to show boot animation?

The fact that it backwards motion happens on every browser, regardless of FPS and processing power suggests the latter. Either way, it looks like a quirky bug.

**Comment by jeffpar** [comment]
I closed this based on the primary issue ("Win95 won't load").  As to the secondary issue ("loading bar appears to go backwards"), well, that's *exactly* how the animation in the first version of Windows 95 looked.  People who recall it animating differently are recalling *later* versions, perhaps also with the Plus Pack installed.  I have the same original version of Windows 95 installed in a VirtualBox VM, and it animates exactly the same way.

![win95originalbootanimation](https://user-images.githubusercontent.com/645749/37979179-c24bd79e-319c-11e8-9228-f5a94160c62d.gif)
