### ISSUE TITLE
This is not necessarily an issue, but more of a request...

### ISSUE THREAD

**Issue by ManyPandas** [jeffpar/pcjs.v1#47]
Would it be possible to add an Apple II emulator to the PCjs project?  Maybe you could create a new project called Applejs.  I am not sure, but I would really appreciate an Apple II Emulator like PCjs.

**Comment by starfrost013** [comment]
I actually want 80486 emulation

**Comment by jeffpar** [comment]
I'm actually going backward in time now, not forward.  Currently working on machines from 1970's and 1960's.  Contributions for other machines are happily accepted, though, provided they fit into the overall framework.
