### ISSUE TITLE
20MB HDD isn't working

### ISSUE THREAD

**Issue by TheMatten** [jeffpar/pcjs.v1#48]
Every tried OS on any machine returns error when trying to check, format or use HDD, for example MS-DOS returns "Invalid drive specification" error with "c:" or "format c:", Minix boot disk returns "Disk errors. Cannot read partition table." with option "h", etc.

**Comment by jeffpar** [comment]
Which machine? I just this tried [this one](http://www.pcjs.org/devices/pcx86/machine/5170/ega/1152kb/rev1/debugger/) and it worked. Note that MS-DOS requires that you run FDISK first to create a DOS partition, and then you can FORMAT C: and begin using it. Other operating systems may have similar procedures that you must run first, too.

**Comment by TheMatten** [comment]
I tried "fdisk c:" on 4mb 5170 with 20mb disk and got "Fixed disk error".
But machine that you tried is ok for me too. Strange...

**Comment by TheMatten** [comment]
Of course I tried fdisk first and then everything I could remember, and
because I wanted to be sure that it's not problem of one OS, I tried few
other OSes and setup discs. But I haven't tried EVERY available machine and
I wrote "20MB HDD not working" because machines with 10MB seemed to be ok.
But maybe it's my fault and everything is ok, then sorry :(.

**Comment by jeffpar** [comment]
Every machine is slightly different, so one particular machine could certainly have a problem. I just need to know what machine you were using.

**Comment by TheMatten** [comment]
IBM PC AT - variants with 4MB RAM and 20MB disc

**Comment by jeffpar** [comment]
Thanks for catching this. I had moved some disk images around in an effort to reduce GitHub Pages build time (I started getting GitHub Pages build timeout errors this week), and I missed an XML file that needed to be updated.  Give the machines a thorough refresh and try again.  I think it should be fixed now.  Thanks.

**Comment by TheMatten** [comment]
Great. And sorry for "EVERY machine", I could be more precise... :D

**Comment by TheMatten** [comment]
Maybe we can mark it as closed :D

**Comment by jeffpar** [comment]
Indeed. Thanks again.
