### ISSUE TITLE
Is there any reason for excluding 80486?

### ISSUE THREAD

**Issue by hlide** [jeffpar/pcjs.v1#52]
I noticed _pcjs_ can handle a 386 processor. For me, 486s are much closer to 386s than Pentiums: no MMX for instance. So, is there any reason not to be able to emulate a 486SX/DX?

**Comment by jeffpar** [comment]
No, it was just a line in the sand. Had to stop somewhere, because there are still a lot of gaps to fill, in terms of hardware emulation (it's not all about CPU emulation).  If anyone else wants to pick up the 486 torch though, that's fine by me.

**Comment by jeffpar** [comment]
I'm think we're going to stop with the 80386, for now.
