### ISSUE TITLE
Feature: Add more hot keys and machines with soft keyboards and fix android keyboard

### ISSUE THREAD

**Issue by gammaboost** [jeffpar/pcjs.v1#54]
If I use a touch device with a virtual keyboard, I am unable to access keys like tab, ctrl, alt, and more. My favourite machine is the IBM PC AT. I like halting it at the start then mounting the MS-DOS 5.0 disk to install it. Then, there is the dos shell. I need the tab key and F10 key to operate the dos shell. Can you maybe have more machines with a soft keyboard or extra hot keys? Thanks. Also, on most android devices, I am unable to access the virtual keyboard on the device. No new characters appear on the screen. Fix that please, or else I will not be able to use the machine when I'm on my Samsung Galaxy Note 4.

**Comment by jeffpar** [comment]
Soft keyboards were recently added to all machines (click the **Keys** button), so hopefully that resolves this issue.  Thanks.
