### ISSUE TITLE
I noticed the milestones you set 3 Years ago...

### ISSUE THREAD

**Issue by Foxlum** [jeffpar/pcjs.v1#55]
@jeffpar i noticed that you set some milestones 3 years ago
Cache Manifest Support and Co-processor Support.

Are you still working on them or just forgot?

**Comment by jeffpar** [comment]
Coprocessor support was added (8087; some 80287 support was added as well but I’m not sure I ever tested it). Cache manifest support was not added.

**Comment by Foxlum** [comment]
ok then... i was wondering why are they still open?

**Comment by jeffpar** [comment]
Milestones removed.
