### ISSUE TITLE
PDP-11/70 doesn't increment the address as data is Deposited

### ISSUE THREAD

**Issue by JamesHagerman** [jeffpar/pcjs.v1#56]
Hi there,

I understand your pdp-11 emulator hasn't received as much focus as some of the other machines, but it seems, currently, as though the address doesn't increment as you Deposit data.

I'm new to PDP-11's so this might be wrong, however, the PDP-11/40 (and 70) js emulator you started from seems to work this way. I also remember reading mention of it in the PDP-11 manual earlier today.

Just a heads up!

Thanks,
James

**Comment by jeffpar** [comment]
Looks like a problem.  Thanks for mentioning it.  Should be an easy fix.

**Comment by jeffpar** [comment]
Should be fixed in v1.60.1 now. Thanks.

**Comment by JamesHagerman** [comment]
Awesome! Good to know! I'll test it when I get a chance!
