### ISSUE TITLE
Unable to Play 'Space Invaders'

### ISSUE THREAD

**Issue by ManyPandas** [jeffpar/pcjs.v1#61]
I am having an issue with PC8080.  To interact with the machine, I must click on the machine window.  However, when I do so the display output of the emulator simply disappears.  If I click off of it, it does not reappear. When I refresh the page the game will reappear for a brief moment while the page reloads. I'm not sure if this is an issue with PCjs or my browser, but I feel it should be looked into.

**Comment by jeffpar** [comment]
Tell me a little about your environment (eg, what web browser and operating system you are using). I just retested with Safari, Chrome, and Firefox (all on macOS), and it seemed to work fine.

**Comment by ManyPandas** [comment]
What are the chances?  Literally right after I submitted this issue report, it started working again!   Not 100% sure what was happening.  It was most likely a problem with my environment, not anything to do with the PC8080 code.  Thank you for responding though!  Have a nice day!

**Comment by jeffpar** [comment]
No problem, thanks.
