### ISSUE TITLE
Save HD doesn't work on Chrome - can improve with Blob/URL

### ISSUE THREAD

**Issue by mihailik** [jeffpar/pcjs.v1#62]
Save HD button doesn't work on Chrome - quick check suggested due to data URI being too large.

A better more scalable approach would be to use `Blob` and `URL` - will also skip unnecessary base64 encode in this case.

I'm trying to implement a PR for that at the moment, actually. Hope to submit soon.

**Comment by jeffpar** [comment]
I’m assuming we can consider this fixed now, thanks to you.
