### ISSUE TITLE
Setup fails cloning disk images

### ISSUE THREAD

**Issue by spock64** [jeffpar/pcjs.v1#77]
Hi,
I'm trying to set up a clone of the site according to the instructions - but this fails as the disk images are under a separate repo!

Is this intentional or is there something else I need to do?

Thanks
Jason

From the log ...

```
Cloning into '/home/j/pcjs/pcjs/disks-cds/cds001'...
Username for 'https://github.com':
```

**Comment by jeffpar** [comment]
I should probably remove those submodules from the project, since they’re optional. For now, clone the repo without them.  The only submodule you probably want is pcjs-demo-disks (which likes to be cloned as disks-demo in the root of the pcjs project).

**Comment by spock64** [comment]
Thanks - I'll give that a go!

**Comment by jeffpar** [comment]
FYI, I've updated the project's submodules so that only the public ones (pcjs-demo-disks and pcjs-game-disks) are referenced now.
