### ISSUE TITLE
Disk image repos missing

### ISSUE THREAD

**Issue by dgelessus** [jeffpar/pcjs.v1#84]
Hi, I'm currently unable to fully update my local clone of PCjs, as it seems that all of the disk image repos (referenced by the `disks-*` submodules in this repo) are missing/inaccessible:

* https://github.com/jeffpar/pcjs-demo-disks
* https://github.com/jeffpar/pcjs-game-disks
* https://github.com/jeffpar/pcjs-pcsig8a-disks
* https://github.com/jeffpar/pcjs-pcsig8b-disks
* https://github.com/jeffpar/pcjs-pdp11-disks

PCjs itself seems to be working fine after the update, and I can load disks that I already have locally from the last time I updated. I just can't use any of the newly added disks or make a new full clone of the repo.

The pcjs.org website now apparently references some different disk repos, but those are also inaccessible:

* https://github.com/jeffpar/pcjs-diskettes
* https://github.com/jeffpar/pcjs-decdisks

Was there some kind of change that I missed and I need do something else to run PCjs locally now?

**Comment by jeffpar** [comment]
The new repo doesn't use submodules, so the pcjs-diskettes and pcjs-decdisks repos don't need to be public.  As for the old repo, well, recreating the old disk repos might be the easiest solution.  I'll look into it.

**Comment by jeffpar** [comment]
I successfully ran `git clone --recurse-submodules https://github.com/jeffpar/pcjs.git` so this should be resolved.  I think this is also a good time to archive the repo, since all active development is now in the [pcjs.org](https://github.com/jeffpar/pcjs.org) repo.
